question_data = [
    {"question": "The chemical symbol for tungsten is W.", "answer": "True"},
    {"question": "The Battle of Hastings took place in 1065.", "answer": "False"},
    {"question": "Venus is the hottest planet in the Solar System.", "answer": "True"},
    {"question": "The human body has 208 bones in adulthood.", "answer": "False"},
    {"question": "The first programmable computer was developed before World War II.", "answer": "True"},
    {"question": "Sound travels faster in air than in water.", "answer": "False"},
    {"question": "DNA stands for Deoxyribonucleic Acid.", "answer": "True"},
    {"question": "The capital city of Canada is Toronto.", "answer": "False"},
    {"question": "An electron carries a negative charge.", "answer": "True"},
    {"question": "The currency of Japan is the Yen.", "answer": "True"},
    {"question": "Albert Einstein won the Nobel Prize for the Theory of Relativity.", "answer": "False"},
    {"question": "The Amazon River is the longest river in the world.", "answer": "False"},
    {"question": "A leap year occurs every 4 years without exception.", "answer": "False"},
    {"question": "The programming language C was developed after Python.", "answer": "False"},
    {"question": "The square root of 144 is 12.", "answer": "True"},
    {"question": "Mercury is the closest planet to the Sun.", "answer": "True"},
    {"question": "The Great Barrier Reef is located in the Atlantic Ocean.", "answer": "False"},
    {"question": "The speed of light is faster than the speed of sound.", "answer": "True"},
    {"question": "Pluto is officially classified as a planet.", "answer": "False"},
    {"question": "The human heart has four chambers.", "answer": "True"},
    {"question": "The boiling point of water is 90°C at sea level.", "answer": "False"},
    {"question": "Light year is a unit of distance.", "answer": "True"},
    {"question": "The tallest mammal is the giraffe.", "answer": "True"},
    {"question": "The Pacific Ocean is smaller than the Atlantic Ocean.", "answer": "False"},
    {"question": "The Mona Lisa was painted by Leonardo da Vinci.", "answer": "True"},
    {"question": "Goldfish have a memory span of only three seconds.", "answer": "False"},
    {"question": "The capital of Brazil is Brasília.", "answer": "True"},
    {"question": "The human body contains more than 600 muscles.", "answer": "True"},
    {"question": "Bamboo is a type of tree.", "answer": "False"},
    {"question": "Shakespeare wrote 'To Kill a Mockingbird'.", "answer": "False"},
    {"question": "The Sun is a star.", "answer": "True"},
    {"question": "A byte consists of 8 bits.", "answer": "True"},
    {"question": "The Sahara is the largest desert in the world.", "answer": "False"},
    {"question": "The chemical formula of water is H2O.", "answer": "True"},
    {"question": "Humans have walked on Mars.", "answer": "False"},
    {"question": "The freezing point of water is 0°C.", "answer": "True"},
    {"question": "The Earth is flat.", "answer": "False"},
    {"question": "Jupiter is the largest planet in the Solar System.", "answer": "True"},
    {"question": "The capital of Italy is Rome.", "answer": "True"},
    {"question": "Penguins can fly.", "answer": "False"},
    {"question": "The square root of 81 is 9.", "answer": "True"},
    {"question": "Mount Everest is located in Africa.", "answer": "False"},
    {"question": "Humans breathe oxygen.", "answer": "True"},
    {"question": "The Moon is a planet.", "answer": "False"},
    {"question": "The Eiffel Tower is in Paris.", "answer": "True"},
    {"question": "Python is named after a snake species.", "answer": "False"},
    {"question": "There are seven continents on Earth.", "answer": "True"},
    {"question": "Saturn is known for its rings.", "answer": "True"},
    {"question": "The capital of India is Mumbai.", "answer": "False"},
    {"question": "An octopus has three hearts.", "answer": "True"},
    {"question": "Sound can travel through a vacuum.", "answer": "False"},
    {"question": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
    {"question": "The human skeleton is made up of over 200 bones.", "answer": "True"},
    {"question": "Electricity travels slower than sound.", "answer": "False"},
    {"question": "Bananas grow on trees.", "answer": "False"},
    {"question": "The smallest prime number is 2.", "answer": "True"},
    {"question": "The Statue of Liberty was a gift from Germany.", "answer": "False"},
    {"question": "The chemical symbol for sodium is Na.", "answer": "True"},
    {"question": "Whales are fish.", "answer": "False"},
    {"question": "The longest bone in the human body is the femur.", "answer": "True"},
    {"question": "The Earth has two moons.", "answer": "False"},
    {"question": "A triangle has three sides.", "answer": "True"},
    {"question": "The speed of sound is faster than light.", "answer": "False"},
    {"question": "The currency of the United Kingdom is the Pound Sterling.", "answer": "True"},
    {"question": "The liver pumps blood through the body.", "answer": "False"},
    {"question": "The tallest building in the world is Burj Khalifa.", "answer": "True"},
    {"question": "Antarctica is the hottest continent.", "answer": "False"},
    {"question": "The capital of Egypt is Cairo.", "answer": "True"},
    {"question": "An atom is smaller than a molecule.", "answer": "True"},
    {"question": "Spiders have six legs.", "answer": "False"},
    {"question": "Water expands when it freezes.", "answer": "True"},
    {"question": "The Sun revolves around the Earth.", "answer": "False"},
    {"question": "The piano has 88 keys.", "answer": "True"},
    {"question": "The chemical symbol for iron is Fe.", "answer": "True"},
    {"question": "Dolphins are reptiles.", "answer": "False"},
    {"question": "The capital of Russia is Moscow.", "answer": "True"},
    {"question": "The human brain is located in the chest.", "answer": "False"},
    {"question": "Lightning is hotter than the surface of the Sun.", "answer": "True"},
    {"question": "A heptagon has eight sides.", "answer": "False"},
    {"question": "The smallest continent is Australia.", "answer": "True"},
    {"question": "The speed of light is approximately 300,000 km/s.", "answer": "True"},
    {"question": "The capital of China is Shanghai.", "answer": "False"},
    {"question": "The Earth rotates on its axis.", "answer": "True"},
    {"question": "Mice are larger than elephants.", "answer": "False"},
    {"question": "The Roman numeral for 50 is L.", "answer": "True"},
    {"question": "Cheetahs are the fastest land animals.", "answer": "True"},
    {"question": "The Pacific Ocean lies between Africa and Europe.", "answer": "False"},
    {"question": "The square root of 49 is 7.", "answer": "True"},
    {"question": "An ostrich can fly.", "answer": "False"},
    {"question": "The human body has five senses traditionally.", "answer": "True"},
    {"question": "The capital of Germany is Berlin.", "answer": "True"},
    {"question": "Glass is made primarily from sand.", "answer": "True"},
    {"question": "Bats are blind.", "answer": "False"},
    {"question": "The longest river in Africa is the Nile.", "answer": "True"},
    {"question": "The currency of the USA is the Euro.", "answer": "False"},
    {"question": "The Earth is the third planet from the Sun.", "answer": "True"},
    {"question": "A hexagon has six sides.", "answer": "True"},
    {"question": "The boiling point of water decreases at higher altitudes.", "answer": "True"},
    {"question": "Venus is farther from the Sun than Mars.", "answer": "False"},
    {"question": "The capital of Spain is Madrid.", "answer": "True"},
    {"question": "Humans have gills.", "answer": "False"},
    {"question": "The largest organ in the human body is the skin.", "answer": "True"},
    {"question": "The chemical symbol for potassium is K.", "answer": "True"},
    {"question": "The Moon produces its own light.", "answer": "False"},
    {"question": "A leap year has 366 days.", "answer": "True"},
    {"question": "The capital of South Korea is Seoul.", "answer": "True"},
    {"question": "The Earth has one natural satellite.", "answer": "True"},
    {"question": "Tigers are herbivores.", "answer": "False"},
    {"question": "Pi is approximately equal to 3.14159.", "answer": "True"},
    {"question": "The Amazon rainforest is located in Asia.", "answer": "False"},
    {"question": "The human body contains trillions of cells.", "answer": "True"},
    {"question": "The capital of Argentina is Buenos Aires.", "answer": "True"},
    {"question": "A square has five sides.", "answer": "False"},
    {"question": "Neptune is the farthest planet from the Sun.", "answer": "True"},
    {"question": "The freezing point of water is 32°F.", "answer": "True"},
    {"question": "Fish can breathe outside water indefinitely.", "answer": "False"},
    {"question": "The currency of India is the Rupee.", "answer": "True"},
    {"question": "The Taj Mahal is located in Delhi.", "answer": "False"},
    {"question": "The capital of Turkey is Ankara.", "answer": "True"},
    {"question": "The Great Wall of China is visible from the Moon.", "answer": "False"},
    {"question": "An adult human has 32 teeth.", "answer": "True"},
    {"question": "The human body has three kidneys.", "answer": "False"},
    {"question": "The capital of Thailand is Bangkok.", "answer": "True"},
    {"question": "Mercury is larger than Earth.", "answer": "False"},
    {"question": "The hardest natural substance is diamond.", "answer": "True"},
    {"question": "The chemical symbol for silver is Ag.", "answer": "True"},
    {"question": "Birds are cold-blooded animals.", "answer": "False"},
    {"question": "The currency of China is the Yuan.", "answer": "True"},
    {"question": "A right angle measures 90 degrees.", "answer": "True"},
    {"question": "The Sun is a planet.", "answer": "False"},
    {"question": "The capital of Pakistan is Islamabad.", "answer": "True"},
    {"question": "Water is composed of hydrogen and oxygen.", "answer": "True"},
    {"question": "Humans have tails.", "answer": "False"},
    {"question": "The currency of Russia is the Ruble.", "answer": "True"},
    {"question": "The Earth takes 24 hours to rotate once.", "answer": "True"},
    {"question": "Sharks are mammals.", "answer": "False"},
    {"question": "The capital of France is Paris.", "answer": "True"},
    {"question": "The speed of sound in air is about 343 m/s.", "answer": "True"},
    {"question": "Mars is known as the Blue Planet.", "answer": "False"},
    {"question": "The chemical symbol for carbon is C.", "answer": "True"},
    {"question": "The capital of Nepal is Kathmandu.", "answer": "True"},
    {"question": "The human body has two lungs.", "answer": "True"},
    {"question": "The Atlantic Ocean is larger than the Pacific Ocean.", "answer": "False"},
    {"question": "The longest day of the year occurs during the summer solstice.", "answer": "True"},
    {"question": "A pentagon has six sides.", "answer": "False"},
    {"question": "The capital of Saudi Arabia is Riyadh.", "answer": "True"},
    {"question": "The speed of light can be exceeded.", "answer": "False"},
    {"question": "An isosceles triangle has at least two equal sides.", "answer": "True"},
    {"question": "The human eye can distinguish millions of colors.", "answer": "True"},
    {"question": "The currency of Europe is the Dollar.", "answer": "False"},
    {"question": "The Earth orbits the Sun once every year.", "answer": "True"},
    {"question": "Camels store water in their humps.", "answer": "False"},
    {"question": "The capital of Indonesia is Jakarta.", "answer": "True"},
    {"question": "The Moon affects ocean tides.", "answer": "True"},
    {"question": "The square root of 100 is 20.", "answer": "False"},
    {"question": "The chemical symbol for oxygen is O.", "answer": "True"},
    {"question": "A kilogram is heavier than a gram.", "answer": "True"},
    {"question": "The largest continent is Europe.", "answer": "False"},
    {"question": "The capital of Mexico is Mexico City.", "answer": "True"},
    {"question": "The boiling point of water is 212°F.", "answer": "True"},
    {"question": "Snakes have legs.", "answer": "False"},
    {"question": "The currency of Bangladesh is the Taka.", "answer": "True"},
    {"question": "The Earth is closer to the Sun than Venus.", "answer": "False"},
    {"question": "The human body has a circulatory system.", "answer": "True"},
    {"question": "The capital of Sri Lanka is Colombo.", "answer": "False"},
    {"question": "The Sun rises in the east.", "answer": "True"},
    {"question": "All metals are magnetic.", "answer": "False"},
    {"question": "The currency of South Korea is the Won.", "answer": "True"},
    {"question": "The longest bone in the human body is the tibia.", "answer": "False"},
    {"question": "The Pacific Ring of Fire is associated with earthquakes and volcanoes.", "answer": "True"},
    {"question": "The capital of Australia is Canberra.", "answer": "True"},
    {"question": "An octagon has eight sides.", "answer": "True"},
    {"question": "The human body produces insulin in the liver.", "answer": "False"},
    {"question": "The currency of Japan is the Yen.", "answer": "True"},
    {"question": "The Earth has a magnetic field.", "answer": "True"},
    {"question": "Polar bears live in Antarctica.", "answer": "False"},
    {"question": "The capital of Nigeria is Abuja.", "answer": "True"},
    {"question": "Water boils faster at higher altitudes.", "answer": "False"},
    {"question": "The chemical symbol for helium is He.", "answer": "True"},
    {"question": "The Great Pyramid of Giza is in Egypt.", "answer": "True"},
    {"question": "The capital of New Zealand is Auckland.", "answer": "False"},
    {"question": "Humans and dinosaurs coexisted.", "answer": "False"},
    {"question": "The currency of Canada is the Canadian Dollar.", "answer": "True"},
    {"question": "The Earth’s core is extremely hot.", "answer": "True"},
    {"question": "The human body has four stomachs.", "answer": "False"},
    {"question": "The capital of Kenya is Nairobi.", "answer": "True"},
    {"question": "The Moon has no atmosphere.", "answer": "False"},
    {"question": "The chemical symbol for nitrogen is N.", "answer": "True"},
    {"question": "The currency of Thailand is the Baht.", "answer": "True"},
    {"question": "An acute angle is greater than 90 degrees.", "answer": "False"},
    {"question": "The Earth is approximately 4.5 billion years old.", "answer": "True"},
    {"question": "The capital of Vietnam is Hanoi.", "answer": "True"},
    {"question": "The Sun is made mostly of hydrogen.", "answer": "True"},
    {"question": "The human body can survive without water for months.", "answer": "False"}
]
