all_colors = [
    "snow", "ghost white", "white smoke", "gainsboro", "floral white",
    "old lace", "linen", "antique white", "papaya whip", "blanched almond",
    "bisque", "peach puff", "navajo white", "lemon chiffon", "mint cream",
    "azure", "alice blue", "lavender", "lavender blush", "misty rose",
    "white", "black", "dark slate gray", "dim gray", "slate gray",
    "light slate gray", "gray", "light gray", "midnight blue", "navy",
    "cornflower blue", "dark slate blue", "slate blue", "medium slate blue",
    "light slate blue", "medium blue", "royal blue", "blue",
    "dodger blue", "deep sky blue", "sky blue", "light sky blue",
    "steel blue", "light steel blue", "light blue", "powder blue",
    "pale turquoise", "dark turquoise", "medium turquoise", "turquoise",
    "cyan", "light cyan", "cadet blue", "medium aquamarine", "aquamarine",
    "dark green", "dark olive green", "dark sea green", "sea green",
    "medium sea green", "light sea green", "pale green", "spring green",
    "lawn green", "green", "chartreuse", "medium spring green",
    "green yellow", "lime green", "yellow green", "forest green",
    "olive drab", "dark khaki", "khaki", "pale goldenrod",
    "light goldenrod yellow", "light yellow", "yellow", "gold",
    "light goldenrod", "goldenrod", "dark goldenrod", "rosy brown",
    "indian red", "saddle brown", "sandy brown", "dark salmon",
    "salmon", "light salmon", "orange", "dark orange",
    "coral", "light coral", "tomato", "orange red", "red",
    "hot pink", "deep pink", "pink", "light pink",
    "pale violet red", "maroon", "medium violet red", "violet red",
    "magenta", "violet", "plum", "orchid", "medium orchid",
    "dark orchid", "dark violet", "blue violet", "purple",
    "medium purple", "thistle", "brown", "firebrick", "chocolate",
    "tan", "wheat", "beige", "burlywood", "peru"
]

colors_against_white =[
    "black", "dim gray", "gray", "slate gray", "dark slate gray", "navy",
    "midnight blue", "blue", "royal blue", "dodger blue", "deep sky blue",
    "steel blue", "dark turquoise", "teal", "dark green", "green",
    "forest green", "sea green", "lime green", "olive drab", "gold",
    "goldenrod", "dark goldenrod", "orange", "dark orange", "coral",
    "tomato", "orange red", "red", "firebrick", "maroon", "brown",
    "chocolate", "saddle brown", "hot pink", "deep pink", "medium violet red",
    "magenta", "purple", "dark violet", "blue violet", "indigo"
]

colors_against_black = [
    "gainsboro",
    "light gray",
    "tan",
    "dark goldenrod",
    "peru",
    "silver",
    "dark sea green",
    "plum4",
    "olivedrab",
    "deep sky blue",
    "cadet blue",
    "medium aquamarine",
    "indian red",
    "pale green",
    "khaki",
    "rosy brown",
    "dark sea green",
    "steel blue",
    "silver",
    "steel blue4",
    "rosy brown",
    "rosy brown4",
    "light blue"
]
